### ISSUE TITLE
TPRM (Third Party Risk Managment) features in CISO Assistant

### ISSUE THREAD

**Issue by cota44ur** [intuitem/ciso-assistant-community#614]
Hi,

We are currently managing third party et supply chain risks with Excel spreasheets.
From one of the latest webinars, I've noted that TPRM features were included in CISO Assistant roadmap.

When can we expect TPRM features in ordre to replace Excel spreadsheets ?

Thanks again for your great and very useful tool

**Comment by ab-smith** [comment]
hello
we will be designing the feature during this summer for development and release between Sept-Oct.
We might add a tooling to import the VSA questionnaire in the meanwhile, the same as we did for CCM, since it has restrictive terms of usage.
I'll close this ticket so that we can keep the exchanges on this on #212 
Thank you @cota44ur for the support and you can star the repo and add a thumbs up on the previous ticket so that we can keep track of its importance to our community :)

**Comment by ab-smith** [comment]
duplicate with #212

**Comment by most122** [comment]
Hello, how come to initiate specific questionnaire for example TRPM Azure cloud or 365 how can we conduct that as I reviewed that i found I can conduct that only using specific frame 
I wish I am clear in my question
